### PR TITLE
upgrade pretext to 2.3.3, refresh files

### PR DESCRIPTION
**Pull request by StevenClontz**
If you accept this pull request, and sync it to your Codespace, you should be able to build both web and web-instructor.

(I'm having trouble building the print version in Codespaces due to the Geogebra interactives, so I'll investigate later.)

You should also be able to Deploy from Codespaces.

You *may* be able to pull this to your computer and things may work. If so, then the file access issues we had are a bug of PreTeXt CLI (caused by using 1.0 project.ptx format with version 2.0, but that's something we want to support), and I'll look closer into it.

### CODE REVIEW

**Comment by tjmagnus** [comment]
I haven't ever got the print to run! Perhaps, it is due to the interactives.

Teresa D. Magnus, Ph.D.
Professor of Mathematics
Director of the Mathematics Program
Department of Mathematics and Computer Science

Rivier University
420 S. Main St.
Nashua NH 03060

(603) 897-8462
________________________________
From: Steven Clontz ***@***.***>
Sent: Wednesday, November 29, 2023 4:56 PM
To: tjmagnus/polyomino ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT]: [tjmagnus/polyomino] upgrade pretext to 2.3.3, refresh files (PR #1)


**EXTERNAL EMAIL**


If you accept this pull request, and sync it to your Codespace, you should be able to build both web and web-instructor.

(I'm having trouble building the print version in Codespaces due to the Geogebra interactives, so I'll investigate later.)

You should also be able to Deploy from Codespaces.

You may be able to pull this to your computer and things may work. If so, then the file access issues we had are a bug of PreTeXt CLI (caused by using 1.0 project.ptx format with version 2.0, but that's something we want to support), and I'll look closer into it.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/tjmagnus/polyomino/pull/1

Commit Summary

  *   5f3c009<https://github.com/tjmagnus/polyomino/pull/1/commits/5f3c009b929ae7a859df9c16e094eaeb4a55c437> upgrade pretext to 2.3.3, refresh files

File Changes

(9 files<https://github.com/tjmagnus/polyomino/pull/1/files>)

  *   M .devcontainer.json<https://github.com/tjmagnus/polyomino/pull/1/files#diff-8c75d30eaaa096649631dde76e321d13a6849c64137f3f7f777429ef9fd6b9e2> (15)
  *   D .devcontainer/devcontainer.json<https://github.com/tjmagnus/polyomino/pull/1/files#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686> (48)
  *   D .devcontainer/postCreateCommand.sh<https://github.com/tjmagnus/polyomino/pull/1/files#diff-047cadacfac3bb0c9fde7443892eb3f394d677a281985d6416b80abf54c2800e> (12)
  *   D .devcontainer/pretext-full/devcontainer.json<https://github.com/tjmagnus/polyomino/pull/1/files#diff-ee470b65ffbb271863b8b645ac9c6a50dfe96331a3f8fa789abd0c7b9c912e84> (48)
  *   M .gitignore<https://github.com/tjmagnus/polyomino/pull/1/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947> (14)
  *   D codechat_config.yaml<https://github.com/tjmagnus/polyomino/pull/1/files#diff-ac9071046554f7011bb0ff593b7ccecc528441e7735d482be3539c25e9fe201f> (41)
  *   M project.ptx<https://github.com/tjmagnus/polyomino/pull/1/files#diff-1552d8b163a63a46dd5803e3b07b9bc9d300bd7c5ab0a90cda94c332227ea040> (61)
  *   D publication/publication-20230728-131542.ptx<https://github.com/tjmagnus/polyomino/pull/1/files#diff-fe1ac4591079fe53ea63f613b642cb85617def39763c2eb506aee65ad5b665ce> (7)
  *   M requirements.txt<https://github.com/tjmagnus/polyomino/pull/1/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552> (3)

Patch Links:

  *   https://github.com/tjmagnus/polyomino/pull/1.patch
  *   https://github.com/tjmagnus/polyomino/pull/1.diff

**Comment by StevenClontz** [comment]
Fixed a couple of files that had gotten out of date. You can now merge this if you want.

**Comment by tjmagnus** [comment]
I have to relearn how to reconcile divergent branches.

Teresa D. Magnus, Ph.D.
Professor of Mathematics
Director of the Mathematics Program
Department of Mathematics and Computer Science

Rivier University
420 S. Main St.
Nashua NH 03060

(603) 897-8462
________________________________
From: Steven Clontz ***@***.***>
Sent: Wednesday, November 29, 2023 5:00 PM
To: tjmagnus/polyomino ***@***.***>
Cc: Magnus, Teresa D ***@***.***>; Comment ***@***.***>
Subject: [EXT]: Re: [tjmagnus/polyomino] upgrade pretext to 2.3.3, refresh files (PR #1)


**EXTERNAL EMAIL**


Fixed a couple of files that had gotten out of date. You can now merge this if you want.

**Comment by StevenClontz** [comment]
join me at https://prose.runestone.academy/dropin now if you need help

**Comment by StevenClontz** [comment]
I can also get your print version working too I think

**Comment by tjmagnus** [comment]
Alas, I am still struggling to get my project to deploy. My attempt last night timed out after over an hour and my attempt 23 minutes ago is still incomplete.

Terri

Teresa D. Magnus, Ph.D.
Professor of Mathematics
Director of the Mathematics Program
Department of Mathematics and Computer Science

Rivier University
420 S. Main St.
Nashua NH 03060

(603) 897-8462
________________________________
From: Steven Clontz ***@***.***>
Sent: Wednesday, November 29, 2023 5:15 PM
To: tjmagnus/polyomino ***@***.***>
Cc: Magnus, Teresa D ***@***.***>; State change ***@***.***>
Subject: [EXT]: Re: [tjmagnus/polyomino] upgrade pretext to 2.3.3, refresh files (PR #1)


**EXTERNAL EMAIL**


I can also get your print version working too I think

**Pull request merged**
